POST http://localhost:8000/api/v1/posts
Content-Type: application/json

{
    "text":"Post by Ironman second post"
}

### get feed post
GET http://localhost:8000/api/v1/posts

### get a post
GET http://localhost:8000/api/v1/posts/661d205b66b93e561ba30b04


### update a post
PATCH  http://localhost:8000/api/v1/posts/661d205b66b93e561ba30b04
Content-Type: application/json

{
    "image":"http://localhost",
    "text":"good day!"
}

### delete a post
DELETE  http://localhost:8000/api/v1/posts/661d214ee18ad09bb6d57d2e

### reply to a post
POST  http://localhost:8000/api/v1/posts/reply/661d205b66b93e561ba30b04
Content-Type: application/json

{
    "text":"you look pretty in that black dress."
}

### like to a post
POST http://localhost:8000/api/v1/posts/like/661d205b66b93e561ba30b04
Content-Type: application/json

