GET http://localhost:8000/api/v1/users

### signup
POST  http://localhost:8000/api/v1/users/signup
Content-Type: application/json

{
    "name":"maaz",
    "username":"maazi@123",
    "email":"maazi@gmail.com",
    "password":"123456"
}

### signin
POST  http://localhost:8000/api/v1/users/signin

### get profile
GET   http://localhost:8000/api/v1/users/profile

### signin
PATCH   http://localhost:8000/api/v1/users/update

### signin
DELETE   http://localhost:8000/api/v1/users/delete