

### signup
POST  http://localhost:8000/api/v1/users/signup
Content-Type: application/json

{
    "name":"Tony Stark",
    "username":"ironman@123",
    "email":"ironman@gmail.com",
    "password":"123456"
}

### signin
POST  http://localhost:8000/api/v1/users/signin
Content-Type: application/json

{
    "email":"spiderman@gmail.com",
    "password":"123456"
}

### get profile
GET   http://localhost:8000/api/v1/users/profile

### update
PATCH   http://localhost:8000/api/v1/users/update
Content-Type: application/json

{
    "username":"ironman",
    "name":"Tony Stark"
}

### follow/unfollow
POST http://localhost:8000/api/v1/users/follow/661ccad9f4334de5bd8d0975


### logout
POST   http://localhost:8000/api/v1/users/logout

### get users
GET  http://localhost:8000/api/v1/users